#!/bin/bash
# Build Humi.app from the SwiftPM executable (no Xcode required).
# Usage: Scripts/build-app.sh [debug|release]
set -euo pipefail

CONFIG="${1:-release}"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
APP_NAME="Humi"
BUNDLE_ID="com.studiorizi.humi"
VERSION="$(cat "$ROOT/VERSION" 2>/dev/null || echo 0.1.0)"
BUILD_DIR="$ROOT/.build/$CONFIG"
DIST="$ROOT/dist"
APP="$DIST/$APP_NAME.app"

echo "▸ swift build -c $CONFIG"
cd "$ROOT"
swift build -c "$CONFIG" --product "$APP_NAME"

echo "▸ Assembling $APP"
rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"

cp "$BUILD_DIR/$APP_NAME" "$APP/Contents/MacOS/$APP_NAME"

# SwiftPM resource bundles (HumiKit's fonts + .lproj, SwiftTerm's). These go in the
# standard Contents/Resources/. NOTE: the Command Line Tools toolchain's generated
# `Bundle.module` accessor does NOT look here (only the .app root + a build-machine
# path), so HumiKit resolves resources via `Bundle.humiResources` (see HumiBundle.swift),
# which checks Contents/Resources/ first. Don't revert to Bundle.module.
for b in "$BUILD_DIR"/*.bundle; do
  [ -d "$b" ] && cp -R "$b" "$APP/Contents/Resources/"
done

# Icon (optional — generated by Scripts/make-icns.sh)
if [ -f "$ROOT/Assets/AppIcon.icns" ]; then
  cp "$ROOT/Assets/AppIcon.icns" "$APP/Contents/Resources/AppIcon.icns"
  ICON_LINE="<key>CFBundleIconFile</key><string>AppIcon</string>"
else
  ICON_LINE=""
fi

cat > "$APP/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleName</key><string>$APP_NAME</string>
  <key>CFBundleDisplayName</key><string>$APP_NAME</string>
  <key>CFBundleIdentifier</key><string>$BUNDLE_ID</string>
  <key>CFBundleExecutable</key><string>$APP_NAME</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>CFBundleShortVersionString</key><string>$VERSION</string>
  <key>CFBundleVersion</key><string>$VERSION</string>
  <key>LSMinimumSystemVersion</key><string>14.0</string>
  <key>LSApplicationCategoryType</key><string>public.app-category.developer-tools</string>
  <key>NSHighResolutionCapable</key><true/>
  <key>NSPrincipalClass</key><string>NSApplication</string>
  <key>CFBundleDevelopmentRegion</key><string>en</string>
  <key>CFBundleLocalizations</key>
  <array>
    <string>en</string>
    <string>ja</string>
    <string>zh-Hans</string>
    <string>pt-BR</string>
    <string>es</string>
    <string>de</string>
  </array>
  $ICON_LINE
</dict>
</plist>
PLIST

# Empty .lproj markers so AppKit/SwiftUI treat the *main* bundle as localised and
# localise the standard menu bar (File / Edit / Window / Help, About / Hide / Quit,
# Cut / Copy / Paste …) to the user's language. Our own strings live in
# Humi_HumiKit.bundle and are resolved via `L(...)`; these dirs just flip the switch.
for lang in en ja zh-Hans pt-BR es de; do
  mkdir -p "$APP/Contents/Resources/$lang.lproj"
done

cat > "$APP/Contents/PkgInfo" <<< "APPL????"

echo "▸ Ad-hoc codesign"
# --deep seals the nested resource bundles in Contents/Resources/ as bundle resources.
codesign --force --deep --sign - "$APP" 2>/dev/null || codesign --force --sign - "$APP"
codesign --verify --verbose=1 "$APP" || echo "  (verify: ad-hoc, expected for a local build)"

echo "✓ Built $APP  (v$VERSION, $CONFIG)"
